apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: natter-api
  labels:
    app.kubernetes.io/name: natter-ingress
    app.kubernetes.io/intance: natter-ingress-1
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/componnent: ingress
    app.kubernetes.io/part-of: natter
    app.kubernetes.io/managed-by: make
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "$service_name.$namespace.svc.cluster.local:$service_port"
spec:
  tls:
    - hosts:
        - api.natter.local
      secretName: natter-tls
  rules:
    - host: api.natter.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: natter-api-service
                port:
                  number: 4567
  ingressClassName: nginx
