apiVersion: v1
kind: ServiceAccount
metadata:
  name: natter-api
  namespace: natter-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: natter-database
  namespace: natter-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: natter-link-preview
  namespace: natter-api
