apiVersion: apps/v1
kind: Deployment
metadata:
  name: natter-database-deployment
  namespace: natter-api
  labels:
    app.kubernetes.io/name: natter-database
    app.kubernetes.io/intance: natter-database-1
    app.kubernetes.io/version: 1.4.197
    app.kubernetes.io/componnent: database
    app.kubernetes.io/part-of: natter
    app.kubernetes.io/managed-by: make
spec:
  selector:
    matchLabels:
      app: natter-database
  replicas: 1
  template:
    metadata:
      labels:
        app: natter-database
    spec:
      securityContext:
        runAsNonRoot: true
      volumes:
        - name: db-password-volume
          secret:
            secretName: db-password
      containers:
        - name: natter-database
          image: apisecurityinaction/h2database:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secrets/datababase"
              readOnly: true
      serviceAccountName: natter-database
